# Generated by Django 3.0.8 on 2020-07-03 06:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('useractivity', '0002_user_model'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_model',
            name='activityperiod',
            field=models.ManyToManyField(to='useractivity.ActivityPeriod'),
        ),
    ]
